name: Download artifact
on:
  push:
    branches:
      - testci
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: openshift.getting-started-tomcat    
      - name: Display structure of downloaded files
        run: ls -R
